# Configuration file for Beckhoff EL3104
vendor_id: 0x00000002
product_id: 0x0c1e3052
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x3101, sub_index: 1, type: uint8}
      - {
          index: 0x3101,
          sub_index: 2,
          type: int16,
          state_interface: position.x,
        }
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: ~, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}