/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

/**/pose_calculator:
  ros__parameters:
    type: pose_calculator/PoseCalculator

/**/pose_broadcaster:
  ros__parameters:
    type: pose_broadcaster/PoseBroadcaster
    pose_name: "pose_calculator/target"
    frame_id: "lasertracker"
